name: SneakyCharacterManager
main: net.sneakymouse.sneakycharactermanager.SneakyCharacterManagerPaper
version: '${version}'
description: '${description}'
website: '${url}'
author: Team Sneakymouse
api-version: '1.20'

dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: false
    LuckPerms:
      load: BEFORE
      required: false
    GSit:
      load: AFTER
      required: true